README.md

Added my profile and also revamped the style for profiles to be formatted as a table

Emmanuel Biose's Profile 

---

README.md

- At the moment we use a wiki, which is separated from the project. When
we change the project, it doesn't have a snapshot of the Wiki, which
means that our code is out of sync with the wiki. By keeping together
the project description, everything can be in one place.

Use the README file as a wiki

---

docs/Project-plan.md

Added a proposed project plan

---

docs/Project-plan.md

Started fleshing out the Project Plan

Added more info to the project plan

---

README.md

Fixed windows 10 dev branch

---

docs/Project-plan.md

please correct if there are issues please

added to content to conflict resolution plan

---

docs/Project-plan.md

- Concluded the conflict resolution
- Added Peer Assessment Plan
- Changed the team composition section
- Added some formatting and spelling changes to previous sections

Added conflict resolution, peer assessment

---

.eslintrc.js
package-lock.json
package.json

- Created an npm script to run linting using ESLint and using
`react-native-comunity` config. Run with `npm run lint`.
- Created script to also fix the linting errors. Run with `npm run
lint-fix`.
- Created a script to delete `node_modules` directory. Run with `npm run
clean`.

Added linting

---

README.md
infra/.githooks/pre-push

- This hook will verify that there is no WIP message in commit
- Also will run npm test and lint before each push
- Need to run `git config core.hooksPath infra/.githooks` before
enabling it

Added pre-push hook

---

.eslintrc.js

Removed linting error for mocking functions with jest.

BAU - Removed linting errors for jest mock functions

---

README.md

Added commands to recreate snapshots. Useful for testing locally.

BAU - Added commands to recreate snapshots

---

.gitignore
.travis.yml

Fixes .travis.yml file as it was failing due to invalid notifications property.

30 fix travis file

---

.travis.yml
android/fastlane/Fastfile

Split build jobs into stages based on branch name and git action type:
* on `pull_request` run only `test`
* on `merge` and `master` do a Beta release
* on `NOT merge` and `master` and `$RELEASE_MASTER` do a master release

30 multiple stages build

---

.travis.yml
android/app/build.gradle
android/build.gradle
infra/ci/beta_patch

No need to hardcode the Android version and to remember to update with each release. It will be copied from `package.json`.

30: Android versioning to be copied from package.json

---

App.js
backend/functions/setups/setup.js

- Fix tech debt flagged by SonarCloud.

BAU: Reduce tech debt

---

android/app/build.gradle
android/build.gradle

- For now using the defaults provided by Firebase

47: Using Firebase Performance to trace application running time

---

.travis.yml
infra/ci/beta_patch

To be used for automatic tagging and beta releases

30: Create a separate beta release branch 

---

package-lock.json
package.json

- Previously people had to remember to point their git hooks towards the
hooks directory, now they will be run by husky. No messing with git
config

BAU: Added git hooks and commit message template via husky

---

ios/MyAwesomeApp.xcodeproj/project.pbxproj
package-lock.json
package.json

Sync code version with git tag release version

BAU: Sync code version with git tag release version

---

.travis.yml
prepare-release

BAU: Separate merge and tagging

---

.travis.yml

BAU: Replaced expired GitHub token

---

prepare-release

Extract checkout function into separate unit

BAU: Extract checkout function into separate unit

---

.travis.yml

Trigger all actions on beta-release only when is push on master

BAU: Trigger all actions on beta-release only when is push on master

---

.travis.yml

Build beta releases from the beta-release branch

30: Build beta releases from the beta-release branch

---

.travis.yml
prepare-release
run

Checkout beta-release for APK packaging

30: Checkout beta-release for APK packaging

---

App.js
backend/functions/routes/heatmaps-coordinates.js
geolocation/geolocation.js
package.json
yarn.lock

Task 5 2 dynamic radius test bcarter97

---

.gitignore
App.js
README.md
__tests__/__snapshots__/App-test.js.snap
backend/functions/routes/heatmaps-coordinates.js
geolocation/geolocation.js
package-lock.json
package.json
yarn.lock

Few more visual features here.
- Firstly, the user can click anywhere on the map to generate a heatmap around them.
- Added a small menu to determine the radius of the search

Task 5 3 click to change with loading indicator bcarter97

---

android/app/build.gradle
android/fastlane/Fastfile
android/fastlane/README.md
android/gradle.properties
docs/release-notes/0-5-0.txt
ios/MyAwesomeApp.xcodeproj/project.pbxproj
package-lock.json
package.json

- Increase version number for release `0.5.0`
- Added Fastlane lane to deploy to the Play Store
* Added zoom-in and zoom-out functionality
* Allows user to choose zoom level
* Calculates heatmap based on national average price
* Allows user to pick a point on the map to calculate the heatmap around that point
* Added issue trigger when app start time is more than 2 seconds
* Separated Firebase environments into dev and beta
* Enhanced the CI/CD pipeline to allow merges from master to beta-release

52 release task 5

---

App.js
backend/functions/index.js
backend/functions/routes/find-nearest-house.js
geolocation/geolocation.js
utils/constants.js

- Long press to change heatmap location
- Short press to display the price of the nearest house
- Added new firebase endpoint to get the price of the nearest house. This implements using the "findOne" query with "near", finding the closest house within 10 meters of the selected location.

Added new endpoint for showing individual houses on click
